
[base]
uniswap_v2_factory = "0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6"
weth = "0x4200000000000000000000000000000000000006"
link = "0x88Fb150BDc53A65fe94Dea0c9BA0a6dAf8C6e196"
uniswap_factory = "0x33128a8fC17869897dcE68Ed026d694621f6FDfD"
uniswap_swap_router = "0x2626664c2603336E57B271c5C0b26F421741e481"
uniswap_v2_router = "0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24"
uniswap_quoter = "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a"
ws_url = "wss://base-mainnet.g.alchemy.com/v2/ea5WW5H1wx60RuKPYgGkWoLpyDrk7e90"
http_url = "http://localhost:18545"
alchemy_url = "wss://base-mainnet.g.alchemy.com/v2/ea5WW5H1wx60RuKPYgGkWoLpyDrk7e90"

[mainnet]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
link = "0x514910771AF9Ca656af840dff83E8264EcF986CA"
uniswap_factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
uniswap_v2_factory = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
uniswap_swap_router = "0x0000000000000000000000000000000000000006"
uniswap_v2_router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
uniswap_quoter = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
ws_url = "ws://localhost:8546"
http_url = "http://localhost:8545"
alchemy_url = "wss://eth-mainnet.g.alchemy.com/v2/ea5WW5H1wx60RuKPYgGkWoLpyDrk7e90"
